print("script 1 from main changed LINE 1")
print("script 1 from main changed LINE 2")
print("script 1 from main changed LINE 3")
print("script 1 from main changed LINE 4")
print("script 1 from main changed LINE 5")

print("script 1 from main changed LINE 6")
print("script 1 from main changed LINE 7")
print("script 1 from main changed LINE 8")
print("script 1 from main changed LINE 9")
print("script 1 from main changed LINE 10")